import type { AgentKind, ExecutionReceipt } from "../model";

export function initials(kind?: AgentKind): string { if (!kind) return "AR"; return { codex: "CX", claude: "CL", cursor: "CU", antigravity: "AG" }[kind]; }
export function relativeTime(timestamp: string): string { const normalized = timestamp.includes("T") ? timestamp : `${timestamp.replace(" ", "T")}Z`; const minutes = Math.max(0, Math.round((Date.now() - new Date(normalized).getTime()) / 60_000)); if (minutes < 1) return "now"; if (minutes < 60) return `${minutes}m`; return `${Math.floor(minutes / 60)}h`; }
export function elapsedTime(timestamp: string): string { const started = new Date(timestamp).getTime(); if (!started || Number.isNaN(started)) return "just started"; const seconds = Math.max(0, Math.floor((Date.now() - started) / 1000)); return seconds < 60 ? `${seconds}s elapsed` : `${Math.floor(seconds / 60)}m ${seconds % 60}s elapsed`; }
export function contextLabel(bytes = 0, budgetBytes = 0): string { if (!bytes) return "Packet not assembled"; const usage = `${Math.max(1, Math.round(bytes / 1024))} KiB`; return budgetBytes ? `${usage} / ${Math.round(budgetBytes / 1024)} KiB` : usage; }
export function usageLabel(receipt: ExecutionReceipt): string { const { inputTokens, cachedInputTokens, outputTokens, totalCostUsd, numTurns } = receipt.usage; const parts = [inputTokens !== undefined ? `${inputTokens.toLocaleString()} in` : undefined, cachedInputTokens !== undefined ? `${cachedInputTokens.toLocaleString()} cached` : undefined, outputTokens !== undefined ? `${outputTokens.toLocaleString()} out` : undefined, totalCostUsd !== undefined ? `$${totalCostUsd.toFixed(4)}` : undefined, numTurns !== undefined ? `${numTurns} turns` : undefined].filter(Boolean); return parts.length ? parts.join(" · ") : "Not reported"; }
export function latencyLabel(receipt: ExecutionReceipt): string | undefined { if (receipt.totalMs === undefined) return undefined; const total = (receipt.totalMs / 1000).toFixed(2); const first = receipt.firstOutputMs === undefined ? "first output unavailable" : `${(receipt.firstOutputMs / 1000).toFixed(2)}s to first output`; const preflight = receipt.preflightMs === undefined ? undefined : `${(receipt.preflightMs / 1000).toFixed(2)}s preflight`; return [`${total}s total`, first, preflight].filter(Boolean).join(" · "); }
export function millisecondsLabel(value: number | undefined): string { return value === undefined ? "—" : `${value.toLocaleString()} ms`; }
