import type { AgentKind, Participant } from "../model";

export function isRunnableParticipant(participant: Participant): boolean { return participant.installed && participant.connectionStatus === "connected" && !["manual", "unavailable"].includes(participant.capabilities.autonomyMode); }
export function canUseChat(participant: Participant): boolean { return participant.kind !== "antigravity" && participant.installed && participant.capabilities.nonInteractiveTurn; }
export function canUseQuickEdit(participant: Participant): boolean { return canUseChat(participant) && participant.capabilities.writeMode; }
export function capabilityChips(participant: Participant): string[] { const chips: string[] = []; if (participant.kind === "antigravity") chips.push("Execution disabled · boundary unverified"); else if (!participant.capabilities.writeMode) chips.push("Quick Edit and Ship writes unavailable"); if (participant.kind === "cursor") chips.push("ask mode · no Windows sandbox"); if (!participant.capabilities.warmSession) chips.push("cold start per turn"); if (participant.kind === "antigravity") chips.push("completion stream, not token deltas", "usage not reported"); if (participant.kind === "cursor") chips.push("usage not reported"); return chips; }
export function mentionedAgentFor(objective: string): AgentKind | undefined { return objective.match(/@(codex|claude|cursor|antigravity)\b/i)?.[1]?.toLowerCase() as AgentKind | undefined; }
export function chatAgentFor(objective: string, participants: Participant[], replyTarget?: AgentKind): AgentKind | undefined { const mentioned = mentionedAgentFor(objective); if (mentioned) return participants.find((participant) => participant.kind === mentioned && canUseChat(participant))?.kind; if (replyTarget) return participants.find((participant) => participant.kind === replyTarget && canUseChat(participant))?.kind; return participants.find(canUseChat)?.kind; }
export function shipAgentFor(objective: string, participants: Participant[]): AgentKind | undefined { const mentioned = mentionedAgentFor(objective); if (mentioned) return mentioned; return participants.find(isRunnableParticipant)?.kind; }
export function autonomyLabel(mode: Participant["capabilities"]["autonomyMode"]): string { return { "isolated-auto": "Isolated auto", "reviewed-auto": "Reviewed auto", "unattended-bypass": "Sandbox bypass", manual: "Manual", unavailable: "Unavailable" }[mode]; }
export function connectionLabel(status: Participant["connectionStatus"]): string { return { connected: "Connected", "sign-in-required": "Sign in required", unverified: "Test connection", "not-installed": "Not installed", failed: "Connection failed" }[status]; }
