import type { NativeEnvironment, Project, RoomMessage, Run } from "./model";

export const seedProject: Project = {
  id: "agent-room",
  name: "Agent Room",
  goal: "Remove manual context transfer between coding agents.",
  repositoryPath: "<repo>",
  branch: "main",
};

export const previewEnvironment: NativeEnvironment = {
  native: false,
  repositoryPath: seedProject.repositoryPath,
  branch: "main",
  participants: [
    {
      kind: "codex",
      name: "Codex",
      installed: true,
      version: "preview",
      state: "ready",
      capabilities: {
        nonInteractiveTurn: true,
        streaming: true,
        structuredOutput: true,
        exactResume: true,
        cancellation: true,
        writeMode: true,
        approvalBridge: true,
        usageReporting: false,
        repositoryScoping: true,
        autonomyMode: "isolated-auto",
        autonomyNote: "Preview of the Codex managed-worktree policy.",
        capabilityProof: ["Preview data only"],
      },
      models: [],
      modelDiscoveryNote: "Enter an exact model value or leave blank for the provider default.",
      supportsEffort: false,
    },
    {
      kind: "claude",
      name: "Claude",
      installed: false,
      state: "unavailable",
      capabilities: {
        nonInteractiveTurn: true,
        streaming: true,
        structuredOutput: true,
        exactResume: true,
        cancellation: true,
        writeMode: true,
        approvalBridge: true,
        usageReporting: false,
        repositoryScoping: true,
        autonomyMode: "unavailable",
        autonomyNote: "Install Claude Code to enable reviewed autonomy.",
        capabilityProof: ["Preview data only"],
      },
      models: [],
      modelDiscoveryNote: "Enter an exact model value or leave blank for the provider default.",
      supportsEffort: false,
    },
    {
      kind: "cursor",
      name: "Cursor",
      installed: false,
      state: "unavailable",
      capabilities: {
        nonInteractiveTurn: true,
        streaming: true,
        structuredOutput: true,
        exactResume: true,
        cancellation: true,
        writeMode: true,
        approvalBridge: false,
        usageReporting: false,
        repositoryScoping: true,
        autonomyMode: "unavailable",
        autonomyNote: "Install Cursor Agent to enable this participant.",
        capabilityProof: ["Preview data only"],
      },
      models: [],
      modelDiscoveryNote: "Recheck in the desktop app to discover supported models.",
      supportsEffort: false,
    },
    {
      kind: "antigravity",
      name: "Antigravity",
      installed: false,
      state: "unavailable",
      capabilities: {
        nonInteractiveTurn: true,
        streaming: false,
        structuredOutput: false,
        exactResume: true,
        cancellation: true,
        writeMode: true,
        approvalBridge: false,
        usageReporting: false,
        repositoryScoping: true,
        autonomyMode: "unavailable",
        autonomyNote: "Install agy to enable this participant.",
        capabilityProof: ["Preview data only"],
      },
      models: ["gemini-3.1-pro-high", "gemini-3.1-pro-low"],
      modelDiscoveryNote: "Preview list only. Recheck in the desktop app for models available to your account.",
      supportsEffort: true,
    },
  ],
};

export const seedRun: Run = {
  id: "welcome",
  objective: "Build a durable room that carries work between coding agents.",
  state: "ready",
  route: [],
  reviewCount: 0,
  revisionCount: 0,
  startedAt: new Date().toISOString(),
};

export const seedMessages: RoomMessage[] = [
  {
    id: "welcome",
    kind: "status",
    sender: "system",
    body: "This room keeps the objective, repository evidence, handoffs, and review findings together.",
    reason: "Start with one objective. Agent Room selects only an available participant.",
    createdAt: new Date().toISOString(),
  },
];
