import type { NativeEnvironment, Project, RoomMessage, Run } from "./model";

export const seedProject: Project = {
  id: "agent-room",
  name: "Agent Room",
  goal: "Remove manual context transfer between coding agents.",
  repositoryPath: "<repo>",
  branch: "main",
};

export const previewEnvironment: NativeEnvironment = {
  native: false,
  attached: true,
  repositoryPath: seedProject.repositoryPath,
  branch: "main",
  contextBudgetBytes: 48 * 1024,
  participants: [
    {
      kind: "codex",
      name: "Codex",
      installed: true,
      version: "preview",
      state: "ready",
      connectionStatus: "connected",
      connectionDetail: "Preview data only",
      capabilities: {
        nonInteractiveTurn: true,
        streaming: true,
        structuredOutput: true,
        exactResume: true,
        cancellation: true,
        writeMode: true,
        approvalBridge: true,
        usageReporting: false,
        repositoryScoping: true,
        warmSession: false,
        autonomyMode: "isolated-auto",
        autonomyNote: "Preview of the Codex managed-worktree policy.",
        capabilityProof: ["Preview data only"],
      },
      models: ["gpt-5.6-sol", "gpt-5.6-terra", "gpt-5.6-luna", "gpt-5.5"],
      modelDiscoveryNote: "Exact maintained Codex model IDs.",
      supportsEffort: true,
      effortOptions: ["low", "medium", "high", "xhigh", "max", "ultra"],
    },
    {
      kind: "claude",
      name: "Claude",
      installed: false,
      state: "unavailable",
      connectionStatus: "not-installed",
      connectionDetail: "Preview data only",
      capabilities: {
        nonInteractiveTurn: true,
        streaming: true,
        structuredOutput: true,
        exactResume: true,
        cancellation: true,
        writeMode: true,
        approvalBridge: true,
        usageReporting: false,
        repositoryScoping: true,
        warmSession: false,
        autonomyMode: "unavailable",
        autonomyNote: "Install Claude Code to enable reviewed autonomy.",
        capabilityProof: ["Preview data only"],
      },
      models: ["claude-opus-5", "claude-opus-4-8", "claude-sonnet-5", "claude-fable-5", "opus", "sonnet", "fable"],
      modelDiscoveryNote: "Exact Claude model IDs.",
      supportsEffort: true,
      effortOptions: ["low", "medium", "high", "xhigh", "max"],
    },
    {
      kind: "cursor",
      name: "Cursor",
      installed: false,
      state: "unavailable",
      connectionStatus: "not-installed",
      connectionDetail: "Preview data only",
      capabilities: {
        nonInteractiveTurn: true,
        streaming: true,
        structuredOutput: true,
        exactResume: true,
        cancellation: true,
        writeMode: true,
        approvalBridge: false,
        usageReporting: false,
        repositoryScoping: true,
        warmSession: false,
        autonomyMode: "unavailable",
        autonomyNote: "Install Cursor Agent to enable this participant.",
        capabilityProof: ["Preview data only"],
      },
      models: ["gpt-5", "sonnet-4-thinking", "claude-opus-4-8"],
      modelDiscoveryNote: "Recheck in the desktop app to discover account models.",
      supportsEffort: true,
      effortOptions: ["low", "medium", "high", "xhigh", "max"],
    },
    {
      kind: "antigravity",
      name: "Antigravity",
      installed: false,
      state: "unavailable",
      connectionStatus: "not-installed",
      connectionDetail: "Preview data only",
      capabilities: {
        nonInteractiveTurn: true,
        streaming: false,
        structuredOutput: false,
        exactResume: true,
        cancellation: true,
        writeMode: true,
        approvalBridge: false,
        usageReporting: false,
        repositoryScoping: true,
        warmSession: false,
        autonomyMode: "unavailable",
        autonomyNote: "Install agy to enable this participant.",
        capabilityProof: ["Preview data only"],
      },
      models: ["Gemini 3.1 Pro (high)", "Gemini 3.1 Pro (low)", "Gemini 3 Flash", "Claude Sonnet 4.6 (thinking)", "Claude Opus 4.6 (thinking)", "GPT-OSS-120b"],
      modelDiscoveryNote: "Preview list only. Recheck in the desktop app for models available to your account.",
      supportsEffort: true,
      effortOptions: ["low", "medium", "high"],
    },
  ],
};

export const seedRun: Run = {
  id: "welcome",
  objective: "Build a durable room that carries work between coding agents.",
  state: "ready",
  route: [],
  reviewCount: 0,
  revisionCount: 0,
  startedAt: new Date().toISOString(),
};

export const seedMessages: RoomMessage[] = [
  {
    id: "welcome",
    kind: "status",
    sender: "system",
    body: "This room keeps the objective, repository evidence, handoffs, and review findings together.",
    reason: "Start with one objective. Agent Room selects only an available participant.",
    createdAt: new Date().toISOString(),
  },
];
