import { ShieldCheck } from "lucide-react";
import type { AgentKind, ExecutionReceipt, NativeEnvironment, RoomMessage, Run } from "../../model";
import { agentNames } from "../../model";
import { contextLabel, millisecondsLabel } from "../../lib/format";
import { VerificationList } from "../conversation";
function ReceiptLine({ label, value }: { label: string; value: string }) { return <div className="inspector-receipt-line"><span>{label}</span><code>{value}</code></div>; }
function providerLabel(participant: AgentKind | string): string { return (agentNames[participant as AgentKind] ?? participant) || "Unknown provider"; }
function costLabel(receipt: ExecutionReceipt): string { const cost = receipt.usage?.totalCostUsd; return typeof cost === "number" && Number.isFinite(cost) ? `$${cost.toFixed(4)}` : "Not reported"; }
export function EvidenceTab({ environment, run, messages, receipts }: { environment: NativeEnvironment; run: Run; messages: RoomMessage[]; receipts: ExecutionReceipt[] }) { const evidence = [...messages].reverse().find((message) => message.kind === "evidence"); return <div className="inspector-tab-content"><p className="status-note"><ShieldCheck size={18} /> Coordinator-owned evidence. Git and process results decide completion, not an agent claim.</p><dl className="inspector-definition-list"><div><dt>Changed files</dt><dd>{evidence?.changedFiles?.length ?? 0}</dd></div><div><dt>Context packet</dt><dd>{contextLabel(run.contextBytes, environment.contextBudgetBytes)}</dd></div><div><dt>Review</dt><dd>{run.degradedReview ? "Same provider" : run.reviewer ? "Independent" : "Pending"}</dd></div><div><dt>Handoff contract</dt><dd>Schema v1</dd></div></dl><details><summary>Agent Room limits</summary><p>48 KiB packet, 20 minute phase, 5 minute idle timeout, one revision, two recovery attempts.</p></details><details><summary>Execution receipts</summary>{receipts.length ? <div className="inspector-receipt-list">{receipts.map((receipt) => <section className="inspector-receipt" key={receipt.id}><ReceiptLine label="Phase" value={receipt.phase} /><ReceiptLine label="Provider" value={providerLabel(receipt.participant)} /><ReceiptLine label="Model" value={receipt.actualModel ?? receipt.requestedModel ?? "Provider default"} /><ReceiptLine label="Timing" value={`${millisecondsLabel(receipt.preflightMs)} preflight · ${millisecondsLabel(receipt.totalMs)} total`} /><ReceiptLine label="Cost" value={costLabel(receipt)} /></section>)}</div> : <p>Receipts appear after the first provider phase. They report run telemetry, not provider account quotas.</p>}</details><details><summary>Verification</summary><VerificationList verification={evidence?.verification ?? []} /></details></div>; }
